name: Deploy a Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 594c48bfc7fad4b7f22602d3332be1dd
          command: pages deploy public --project-name=alianzasporcolombia --branch=main --commit-dirty=true
